<a href="https://colab.research.google.com/github/Karrew9/BinTree/blob/main/Numpy_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Примечание:** здесь под словами массив и вектор понимается одномерный **np.array**, например $[1, 2, 3]$.

Под словами матрица и 2D-массив понимается двумерный **np.array**, например $[[1, 2, 3], \quad [4, 5, 6]]$.

Под словами 3D-массив, тензор понимается трёх- и более мерный **np.array**, например $[ [[1, 2, 3], \; [4, 5, 6]], \quad [[7, 8, 9], \; [10, 11, 12]]]$.


#### 1. Импортируйте библиотеку **numpy**, назвав её **np** (★☆☆)

#### 2. Создайте нулевой массив длины 100 по крайней мере 3 способами. (★☆☆)


#### 3. Как найти размер памяти занимаемый массивом? (★☆☆)

#### 4. Создайте массив длины 100 из произвольных чисел, каждый пятый элемент которого равен 1. Решить по крайней мере 3 способами. (★☆☆)


#### 5. Создайте массив целых чётных чисел от 10 до 99. (★☆☆)


#### 6. Создайте массив из 100 случайных чисел, равномерно распределённых на интервале от 0 до 150.

#### 7. Создайте массив размера 100 случайных чисел от 0 до 1, за исключением границ отрезка 0 и 1. (★★☆)

#### 8. Создайте массив из 100 случайных чисел и замените 10 максимальных из них на нули. (★★☆)

#### 9. Инвертировать массив по крайней мере 3-мя способами. (★☆☆)


#### 10. Создайте массив из 100 случайных чисел, отсортируйте его не менее чем 5-ю способами. Измерьте время работы каждого алгоритма. (★★☆)

#### 11. Создайте массив из 30 чисел. Случайным образом замените 10 элементов массива на нули. Найдите индексы нулевых элементов. (★☆☆)


#### 12. Что эквивалентно методу **enumerate** для массивов **numpy**? (★★☆)

#### 13. Задан массив из 100 случайных целых чисел, распределенных от 0 до 100. Поменяйте знак у всех элементов массива, которые больше 10, но меньше 30. (★☆☆)

#### 14. Что выведет следующий скрипт? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 15. Каковы результаты следующих выражений?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 16. Как округлить вверх массив с плавающей запятой?  (★☆☆)

#### 17. Даны два случайных массива, проверьте, равны ли они (★★☆)

#### 18. Даны два массива случайных целых чисел, распределённых в одинаковом числовом промежутке. Найти общие значения. (★☆☆)

#### 19. Извлеките целую часть случайного массива положительных чисел, используя 4 разных метода. (★★☆)

#### 20. Дан массив из 100 случайных целых чисел и произвольное целое число. Найти ближайший к этому числу элемент массива и вывести его индекс.  (★★☆)

#### 21. Создайте случайный вектор размером 100 и найдите среднее значение, дисперсию, стандартное отклонение. Использовать по крайней мере 2 способа. (★☆☆)

#### 22. Создайте рандомный массив и выполните стандартизацию: из каждого элемента вычесть среднее этого массива, полученное число поделите на стандартное отклонение.

#### 23. Косинусное расстояние
Даны два массива (вектора) одинаковой длины. Мерой сходства векторов служит косинусное расстоние:
$$
\cos φ = \frac{a \cdot b}{|a|\cdot |b|},
$$
где $φ$ - угол между векторами, $a \cdot b$ - скалярное произведение, $|a|$ - длина (мера) вектора.

Определите косинусное расстояние между этими векторами. Что можно сказать об их сходстве, различии?

#### 24. Дан массив целых чисел. Построить новый массив с 3 последовательными нулями, чередующимися между каждым значением исходного. (★★★)

#### 25. Создайте матрицу $3 \times 3$ со значениями от 0 до 8 (★☆☆)

#### 26. Создайте единичную матрицу $3 \times 3$. (★☆☆)


#### 27. Создайте числовую матрицу 3 на 5 со случайными целыми значениями. Со случайными дробными значениями. (★☆☆)


#### 28. Создайте матрицу $5 \times 5$ со значениями строк от 0 до 4 по крайней мере 3 способами. (★★☆)

#### 29. Создайте матрицу $10 \times 10$ со случайными значениями и найдите минимальное и максимальное значения по крайней мере 3 способами. (★☆☆)

#### 30. Создайте квадратную матрицу произвольного порядка с единицами на границе и нулями внутри по крайней мере 3 способами. (★☆☆)

#### 31. Добавьте границу из нулей вокруг квадратной матрицы. Например матрицу $5 \times 5$ из единиц нужно окружить нулями, чтобы она превратилась в матрицу 7 на 7. (★☆☆)

#### 32. Реализовать алгоритм обхода матрицы размера $n \times n $:

а) ходом змейки (★☆☆)

б) ходом улитки (★★☆)

в) ходом диагональной змейки (★★★)

#### 33. Создайте матрицу 5 на 5 со значениями $1, 2, 3, 4$ ниже главной диагонали (★☆☆)

#### 34.Создайте матрицу $8\times8$ и залейте ее шахматным узором
Пояснение к заданию: не используйте функцию **tile**. (★☆☆)


#### 35. Умножьте матрицу $5\times3$ на матрицу $3 \times 2$ двумя способами. (★☆☆)

#### 36. Сгенерируйте стандартную матрицу Гаусса  (★★☆)
Тут речь о двумерном нормальном (Гауссовом) распределении. Стандартность означает, что среднее $\mu = 0$, а стандартное отклонение $\sigma = 1$.  

#### 37. Дана произвольная матрица размера $(m, n)$. Как случайным образом разместить $p$ элементов $(p < m \cdot n)$ в матрице (★★☆)

#### 38. Вычтите из элементов матрицы среднее значение каждой строки.  (★★☆)
Пояснение к заданию: необходимо вычислить среднее значение каждой строки матрицы и вычесть его из элементов соответствующей строки  

#### 39. Как отсортировать матрицу по $j$-му столбцу? По $i$-й строке? (★★☆)

#### 40. Как определить, есть ли в данной матрице нулевые столбцы? (★★☆)

#### 41. Дано произвольное число. Найдите ближайшее к данному числу значение в матрице.  (★★☆)

#### 42. Для двух массивов, $x$ и $y$, построить матрицу Коши:
$$c_{ij} = \frac1{x_i - y_j}.$$

#### 43. Как распечатать все значения многомерного массива большого размера? (★★☆)
Пояснение: print выводит на экран только часть массива

#### 44. Рассмотрим массив $a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]$, как сгенерировать матрицу $A = [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], ..., [11, 12, 13, 14]]$? (★★★)
Задача моделирует создание массива с окнами заданной ширины от исходного массива. Далее к этому массиву с окнами можно применять разные агрегирующие функции.  

#### 45. Вычислите ранг матрицы по крайней мере 2 способами. (★★★)

#### 46. Извлеките все смежные блоки размером $3 \times 3$ из случайной матрицы размером $10 \times 10$ (★★★)
Дополнение к заданию: Конкретно в этой задаче под смежные (contiguous) блоки подразумевается результат движения окна заданного размера с шагом 1. Но вообще говоря в англоязычных статьях смежные (contiguous) блоки матрицы или памяти подразумеваются рядом стоящие(имеющие общую границу) непересекающиеся блоки. Хотя в некоторых задачах на leetcode встречалась и такая пересекающаяся формулировка, но только она дополнялась примерами.  
Если представить что исходная матрица - квадратная размером $(N, N)$, а размер окна size_window = $s_w$. Тогда кол-во смежных блоков = $(N-s_w)\cdot (N-s_w)$.


#### 47. Создайте класс Matrix, реализуйте основные матричные операции (сложение, умножение, транспонирование). (★★☆)

#### 48. Создайте подкласс, где $a[i, j] = a[j, i]$. (★★★)

#### 49. Создайте матрицу $8 \times 8$ и заполните её шахматным узором, используя функцию **tile**. (★☆☆)

#### 50. Рассмотрим матрицу $16 \times 16$. Найдите сумму элементов в каждом из непересекающихся блоков $4 \times 4$. (★★★)
Дополнение к заданию: В данном случае подразумевается стандартное блочное (клеточное) разбиение матрицы - блоки при разбиении не пересекаются. Кроме этого в условии задачи разбиение происходит на полные блоки 4 на 4 так как размер исходной матрицы 16 на 16. Но в случае, если размер блока не будет делить размер матрицы без остатка подразумевается что блочное разбиение в этом случае будет оставлять блоки меньше заданного размера слева и снизу.

#### 51. Как получить $n$ наибольших значений массива?  (★★★)
Уточнение к заданию: В этой задаче целесообразно сделать акцент на очень больших массивах и обратить внимание на скорость выбранных методов  
Также целесообразно уточнить многомерный или одномерный массив.

#### 52. Даны два произвольных числовых массива. Постройте их декартово произведение. (★★★)


#### 53. Создайте матрицу $100 \times 100$, представляющую декартово произведение $[0,1] \times [0,1]$. (★★☆)

#### 54. Рассмотрим матрицу размера $10 \times 3$ из произвольных чисел. Извлеките строки, в которых все элементы совпадают (например, $[2, 2, 2]$). Извлеките строки, в которых все элементы различны (например, $[2, 3, 4]$). (★★★)

#### 55. Преобразуйте массив целых чисел в матричное двоичное представление этих чисел (★★★)
Пояснение: допустим на входе массив $[0, 1, 8]$ тогда двоичное представление чисел
```python
0 (десятичное число) = 0b 0 (двоичное представление)
1 (десятичное число) = 0b 1 (двоичное представление)
8 (десятичное число) = 0b 1000 (двоичное представление)
```
$$8 = 1 \cdot 2^3 + 0 \cdot 2^2 + 0 \cdot 2^1 + 0 \cdot  2^0$$  
так как для записи числа 0b 1000 необходимо 4 (четыре) столбца, то на выходе будем иметь матрицу  
```python
[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 0]]
```
где первая строка соответвует числу 0, вторая строка числу 1 и последняя строка числу 8.

подразумевается, что числа положительные, иначе придется выделять отдельный столбец

#### 56. Дана матрица. Извлечь уникальные строки. (★★★)

#### 57. Дана двумерная матрица. В первом столбце имена, во втором фамилии. Нужно написать функцию, которая будет возвращать одномерный вектор с именами и фамилиями через пробел (★★★)

#### 58. Рассмотрим случайную матрицу $10 \times 2$, представляющую декартовы координаты, преобразуйте их в полярные координаты. (★★☆)

#### 59. Рассмотрим случайный вектор размера $5 \times 2$, представляющий координаты. Найдите расстояния от точки до точки, результат представьте в виде матрицы. Таким образом должна получиться матрица $5 \times 5$, где элемент с индексом $[i, j]$ будет растоянием между точкой $i$ и $j$.  (★★☆)

#### 60. Как прочитать следующий файл? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 61. Как умножить имеющийся массив размерности $(5,5,3)$ на массив с размерами $(5,5)$? (★★★)    

#### 62. Поменять местами две строки матрицы. (★★★)

#### 63. Напишите функцию **rotate**, принимающую двумерную матрицу и один из углов поворота:
$$
90^\circ, \, 180^\circ, \, 270^\circ, \, 360^\circ.
$$
Функция должна вернуть новую матрицу соответствующую заданному повороту по часовой стрелке. Функцию **np.rot90()** использовать нельзя.

#### 64. Представим, что в массиве ниже записаны оценки, полученные на экзамене. С помощью функции **np.where()** создайте новый массив, в котором будет записано "Зачет", если соответствующее значение в исходном массиве больше либо равно трем, в противном случае должно быть записано "Незачет".

Подсказка: слова "Зачет" и "Незачет" не обязательно преобразовывать в списки той же длины, что и список с оценками, можно просто вписать их вторыи и третьим параметрами в функцию **np.where()**.

#### 65. Каков результат следующих выражений ? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 66. Какие действия над вектором $Z$ разрешенные? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 67. Рассмотрим тензор размера $(m, n, p)$. Каков индекс $(x, y, z)$ элемента, имеющего порядковый номер $k$?  
Пояснения к заданию: счет элементов подразумевался с 1, а не с нуля.


#### 68. Нормализовать матрицу случайных значений $5 \times 5$   (★☆☆)

**!!!Внимание!!!** в английском языке есть два понятия *standardization* и *normalization*, которые означают стандартизация и нормализация. Эти понятия различаются. Нормализация - это операция приведения матрицы к норме. При этом нормы бывают разные (подробнее о нормах можно посмотреть по [ссылке](https://ru.wikipedia.org/w/index.php?title=%D0%9D%D0%BE%D1%80%D0%BC%D0%B0_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B&stable=1)). В оригинале ответом является стандартизация, а не нормализация. Я посчитал это ответ неверным и привел решение для нормализации.  

***Уточнение для условия упражнения:***  
Давайте нормализуем матрицу по $L_1$ норме. Это означает что после нормализации сумма элементов в каждой сроке матрицы будет давать единицу.  

#### 69. Дан массив 100 целых чисел, многие из которых повторяются. Найти моду - наиболее часто встречающееся значение в массив, по крайней мере 3 способами.

#### 70. Как получить даты вчера, сегодня и завтра? (★☆☆)

#### 71. Как получить все даты, соответствующие июлю 2025 года? (★★☆)

#### 72. Как получить суммы по двум последним осям заданного четырехмерного массива? (★★★)

#### 73. Как вычислить средние значения подмножеств заданного одномерного массива Z, используя вектор I того же размера, описывающий индексы подмножеств? (★★★)
Пояснения к задаче: предположим, что у вас есть какой-нибудь вектор Z в котором указано время ответа сервера на запрос в секундах за последние N запросов. При этом в другом векторе I записанны номера (индексы) соответствующих серверов к которым были адресованны эти запросы. Вам нужно создать вектор mean_Z_I в котором каждому номеру сервера из вектора I соответствовало бы среднее время ответа по запросам из вектора Z (то есть сумма всех минут ответа сервера поделенное на кол-во запросов к этому серверу). При этом, чтобы в полученном векторе mean_Z_I были рассчитаны все имеющиеся сервера с номерами от 0 до np.max(I). То есть если сервера под номером 2 нет в списке I, то в полученном векторе соответствующий элемент mean_Z_I[2] = np.nan.

#### 74. Дан массив длины 20. Рассчитать 4-периодные скользящие средние на 5 периодов вперёд. (★★☆)

#### 75. Ниже дана система линейных уравнений $AX = B$. Решить её по крайней мере тремя способами. (★★★)

$$
\left\{
    \begin{matrix}
    x  + 2y + 3z = 6, \\
    4x + 5y + 6z = 9, \\
     7x + 8y  = -6.
    \end{matrix}
\right.
$$

#### 76. Напишите функцию stairs, принимающую вектор и возвращающую матрицу, в которой каждая строка является копией вектора со смещением.

```python
print(stairs(np.arange(3)))
[[0 1 2]
 [2 0 1]
 [1 2 0]]
 ```

#### 77. Интегралы (★★☆)
Вычислить интегралы (а) и (б) по формулам левых, правых и средних прямоугольников при $n=10$, оценивая точность с помощью сравнения полученных результатов.
$$
  а) \int\limits_{0.6}^{1.4} \frac{\sqrt{x^2+5} \, dx}{2x+\sqrt{x^2+5}}
$$
$$  
   б) \int\limits_{0.2}^{0.8} \frac{\sin(2x+0.5) \, dx}{2+\cos(x^2+1)}
$$

#### 78. Дано цветное изображение. Преобразуйте его в чёрно-белое (оттенки серого). (★★★)
Пояснение: Обычная картинка на компьютере хранится в виде тензора размера (ширина, высота, количество каналов). Длина и ширина в пикселях. Количество каналов - 3 (*RGB*) или 4 (*CMYK*). Например $(640, 480, 3)$. Для отображения тензора можно использовать функцию
```python
from matplotlib.pyplot import imread
img = imread('...<здесь путь>.../image.jpg')
```
или
```python
from imageio import imread
img = imread('...<здесь путь>.../image.jpg')
```

Чтобы превратить цветную RGB-картинку в Grayscale нужно использовать свёртку
$$
Y = 0.299 R + 0.587 G + 0.114 B.$$
То есть три цвета превращаются в один. Получаем тензор размера (640, 480, 1).
Вам надо решить задачу, как тензор размера (x, y, 3) превратить в тензор (x, y, 1).